printf("-Nr  %d [No of SPECIES = %d]\n", No_of_SPECIES, No_of_SPECIES);
printf("-Nc  %d [No of COLUMNS = %d]\n", No_of_COLUMNS, No_of_COLUMNS);
printf("-NR  %d [REPLICATES = %d]\n", REPLICATES, REPLICATES);
printf("-NT  %d [No of TRANSECTS  = %d]\n", No_of_TRANSECTS, No_of_TRANSECTS);
printf("-pC  %g [Colonization Rate (C)= %g]\n", Colonization_Rate, Colonization_Rate);
printf("-pE  %g [Extinction Rate   (E)= %g]\n", Extinction_Rate, Extinction_Rate);
printf("-pR  %d [-pR 1: Model parameters (C,E) are given as true rates]\n", RATES);
printf("        [-pR 0: Model parameters (C,E) are given as transition probabilities]\n");
printf("-pD  %g [Detection Probability = %g]\n", Detectability_Value, Detectability_Value);
printf("-pF  %g [Probability of species presence at time 0 = %g]\n", Phi_0, Phi_0);
